### ISSUE TITLE
Updating Play Time causes HTTP 400.

### ISSUE THREAD

**Issue by chicagoandy** [pantherale0/pynintendoparental#4]
## System Information

version | core-2023.11.1
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.59
arch | x86_64
timezone | America/New_York
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4993
Installed Version | 1.33.0
Stage | running
Available Repositories | 1337
Downloaded Repositories | 24

</details>

<details><summary>AccuWeather</summary>

can_reach_server | ok
-- | --
remaining_requests | 19

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.1
-- | --
update_channel | stable
supervisor_version | supervisor-2023.11.0
agent_version | 1.6.0
docker_version | 24.0.6
disk_total | 62.3 GB
disk_used | 39.1 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Studio Code Server (5.14.2), Duck DNS (1.15.0), Samba share (12.0.0), Home Assistant Google Drive Backup (0.111.1), NGINX Home Assistant SSL proxy (3.5.0), Advanced SSH & Web Terminal (16.0.1), PostgreSQL (1.0.0), Mosquitto broker (6.3.1), TeslaMate (0.20.1), Grafana (9.1.1), SQLite Web (3.10.0), JupyterLab (0.12.1), ESPHome (2023.10.6)

</details>

<details><summary>Dashboards</summary>

dashboards | 6
-- | --
resources | 12
views | 29
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | November 6, 2023 at 4:22 PM
-- | --
current_recorder_run | November 14, 2023 at 4:56 AM
estimated_db_size | 335.66 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Sonoff</summary>

version | 3.5.3 (a8c6d45)
-- | --
cloud_online | 1 / 1
local_online | 1 / 1
debug | failed to load: 

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/pantherale0/ha-nintendoparentalcontrols/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Nintendo Parental Controls mobile app

- [X] I have checked the configuration of the mobile app and the switch device is registered.
- [X] I experience this issue if I test again with the tested configuration in the readme.
- [X] This issue does not happen when tested with the tested configuration in the readme.

### Describe the issue

After succesfully updating the play_time_limit to '0:00:00', (to disable play), I am now unable to re-enable play by setting a different play_time_limit.    This is generating a http 400 error.

[home-assistant_nintendo_parental_2023-11-14T13-26-11.465Z.log](https://github.com/pantherale0/ha-nintendoparentalcontrols/files/13349317/home-assistant_nintendo_parental_2023-11-14T13-26-11.465Z.log)

### Reproduction steps

1.  Update the Play time Limit to '0:00:00'.   Device is locked.
2.  Update the Play time Limit to a time > now.    HTTP error 400 is thrown.
3.
...

### Debug logs

```text
2023-11-14 08:34:27.029 DEBUG (MainThread) [custom_components.nintendo_parental.time] Got request to update play time for device eb8321980e32d47d to 11:00:00
2023-11-14 08:34:27.741 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140008647113920] ('HTTP Exception', 'HTTP Error', 400)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 230, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 2035, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2072, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 876, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/time/__init__.py", line 36, in _async_set_value
    return await entity.async_set_value(service_call.data[ATTR_TIME])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/nintendo_parental/time.py", line 76, in async_set_value
    await self._device.update_max_daily_playtime(minutes)
  File "/usr/local/lib/python3.11/site-packages/pynintendoparental/device.py", line 92, in update_max_daily_playtime
    await self._set_parental_control_setting()
  File "/usr/local/lib/python3.11/site-packages/pynintendoparental/device.py", line 71, in _set_parental_control_setting
    await self._api.send_request(
  File "/usr/local/lib/python3.11/site-packages/pynintendoparental/api.py", line 91, in send_request
    raise HttpException("HTTP Error", response.status)
pynintendoparental.exceptions.HttpException: ('HTTP Exception', 'HTTP Error', 400)
2023-11-14 08:34:29.808 WARNING (MainThread) [pynintendoparental] Unable to update monthly data for eb8321980e32d47d as this device does not report monthly data.
2023-11-14 08:34:30.005 DEBUG (MainThread) [custom_components.nintendo_parental] Finished fetching nintendo_parental data in 1.251 seconds (success: True)

Full logs attached to issue.
```

### Diagnostics dump

not available.

**Comment by pantherale0** [comment]
Thanks, I've been able to replicate this too so will take a look. Nintendo might have changed something their end.

**Comment by pantherale0** [comment]
This error actually comes from Nintendo as below:

```"errorCode":"invalid_params",
"title":"ConstraintViolationException",
"detail":"createOrUpdate.arg3.playTimerRegulations.dailyRegulations.timeToPlayInOneDay.limitTime {org.hibernate.validator.constraints.Range.message}"
```

I'll need to test with the latest version of the app, perhaps 11 hours is something Nintendo doesn't allow.

Note: for this entity the time platform is used as a duration instead of a literal time of day, so setting 11 hours would allow a max screen time of 11 hours, it **won't** prevent access at 11am.

**Comment by chicagoandy** [comment]
Thanks for that note, and I was interpreting it wrong.

To clarify, I want to turn off the Switch at 9:00pm.   I can do that by setting a Play Time of 0:00:00 ?   And at 8:00am, when I want to turn it back on, I can do that by turning off the Alarm switch.

**Comment by pantherale0** [comment]
Yes, when you want to disable / turn off the switch. Set the play time to 0:00:00. When you want it to work again you can either use the alarm switch which bypasses the alarms (like pressing the disable alarms button on the app) or you can update the play time to a maximum allowed amount of time to play.

I think it works best if the per day limits are disabled, although I replaced that for a schedule in home assistant and an automation (for me mostly everything is dependent on home assistant anyway which is hosted on a cluster of proxmix hosts + replicated to allow for failover).

I'm going to close this as won't fix, the absolute maximum is set by Nintendo and there isn't a way around, at least not with the APIs anyway, I could code some things in but the idea of the integration is to be as flexible as possible with the use of home assistant automations / scenes / scripts for more advanced functionality.
