### ISSUE TITLE
Can't retrieve the access token

### ISSUE THREAD

**Issue by glaforest** [pantherale0/pynintendoparental#7]
Hi, when I login to the nintendo website nothing happens. 

This redirect uri is generated : redirect_uri=npf54789befb391a838. I tried in the app, in chrome and in Safari and i get an error that the shema is not recognized. On my Iphone, I am redirected to the nintendo switch app and nothing happens. Than you.
<img width="1132" alt="Screenshot 2024-04-25 at 12 18 29 AM" src="https://github.com/pantherale0/pynintendoparental/assets/7120279/eccd85b2-c67c-4466-96d4-98b1e1562ae0">

**Comment by pantherale0** [comment]
Closing as duplicate. Please see:

https://github.com/pantherale0/ha-nintendoparentalcontrols/issues/74
https://github.com/pantherale0/ha-nintendoparentalcontrols/issues/80
